# Generated by Django 4.2.19 on 2025-08-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='navbar_icon_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='revenuemodel',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
