# Generated by Django 4.2.19 on 2025-06-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='item_finished',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
