# Generated by Django 4.2.19 on 2025-06-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dictionary', '0002_itemmodel_item_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='billmodel',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
