# Generated by Django 4.2.19 on 2025-07-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dictionary', '0003_billmodel_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='item_available',
            field=models.BooleanField(default=True),
        ),
    ]
