# Generated by Django 4.2.19 on 2025-07-01 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dictionary', '0004_itemmodel_item_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmodel',
            name='item_available',
        ),
    ]
