# Generated by Django 5.2 on 2025-07-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dictionary', '0005_remove_itemmodel_item_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='billmodel',
            name='delivery_addres_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billmodel',
            name='delivery_addres_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
