# Generated by Django 5.2 on 2025-07-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dictionary', '0006_billmodel_delivery_addres_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billmodel',
            name='current_loc',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
