# Generated by Django 4.2.19 on 2025-07-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dictionary', '0007_billmodel_current_loc'),
    ]

    operations = [
        migrations.AddField(
            model_name='billmodel',
            name='paid_type',
            field=models.CharField(blank=True, choices=[('fully_paid', 'fully_paid'), ('partially_paid', 'partially_paid'), ('not_paid', 'not_paid')], default='not_paid', max_length=100, null=True),
        ),
    ]
